name: Build for macOS M4

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        # 这里指定使用 lua54 特性，它会自动触发我们刚才改的 vendored 静态编译
        run: cargo build --release --features lua54

      - name: Export SO
        run: |
          mkdir -p output
          # 搜索生成的动态库并重命名为 wordninja.so
          find target/release -maxdepth 1 -name "libwordninja_rs_lua.dylib" -exec cp {} output/wordninja.so \;

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: wordninja-macos-m4-lua54
          path: output/wordninja.so
